spring.application.name=furima-c

# ポート設定
server.port=8080

# データベース接続設定 (Docker環境に合わせた設定)
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://db:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres

# Flyway設定
spring.flyway.enabled=true
spring.flyway.baseline-on-migrate=true

# MyBatis設定
mybatis.configuration.map-underscore-to-camel-case=true